@Asilo_Notificaciones_Api_HostAddress = http://localhost:5240

POST {{Asilo_Notificaciones_Api_HostAddress}}/api/notificaciones
Content-Type: application/json

{
  "paciente": "Ana Maria Reyes Ordóñez",
  "familiar": "Ana Maria Reyes Ordóñez",
  "correoFamiliar": "nincy2002r@gmail.com",
  "medicoReferido": "Dra. Maria Perez",
  "especialidad": "Cardiologia",
  "motivo": "Prueba de notificación del sistema"
}

###